#docker-compose.yml
version: '3'


services:
  mongo:
    image: mongo
    container_name: db-mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /home/ivan/workspace/api/data
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
